apiVersion: v1
kind: Service
metadata:
  name: myapp-service
# spec for the service, including type, ports, and selector
spec:
  type: NodePort
  # input port for the service, target port for the container, and node port for external access
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  # selector to match the labels of the pods to route traffic to
  # links the service to the pods it manages
  selector:
    env: production